py_binary(
    name = "server",
    srcs = ["server.py"],
    deps = [
        "//protos:hello_python_proto",
        "//protos:hello_grpc",
        "@pip//:grpcio",
        "@pip//:protobuf",
    ],
) 